#ifndef _CONSTANT_H_
#define _CONSTANT_H_

typedef enum {
	DB_TEMP_BLOCK = 1,
	DB_SCHEMA_BLOCK,
	DB_USER_BLOCK,
	DB_DATABASE_BLOCK,
	DB_DELETED_BLOCK,
	DB_TABLE_BLOCK,

	DB_VARCHAR_TYPE = 100,
	DB_INT_TYPE = 354,
	DB_FLOAT_TYPE,
}DBenum;

// STATIC_ASSERT(sizeof(enum e_DBenum) == 1);

#endif